import Navbar from '@/components/navbar/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'
import Contact from '@/components/contact/contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lego App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Contact/>
        <Footer/>
        </body>
    </html>
  )
}
